%YAML:1.0 # need to specify the file type at the top!

lidar:
  enabled: true
  max_n: 1
  do_calib_dt: false
  do_calib_ext: false
  init_cov_dt: 1e-4
  init_cov_ex_o: 1e-4
  init_cov_ex_p: 1e-3
  max_range: 10.0
  min_range: 0.1
  chi2_mult: 1 
  raw_do_downsample: false
  raw_downsample_size: 0.01
  raw_noise: 3.0
  raw_remove_motion_blur: false # required to set v_angles and h_angles correctly
  raw_point_dt: 1e-6
  map_do_downsample: true
  map_downsample_size: 0.05
  map_noise: 1.0
  map_ngbr_num: 5
  map_ngbr_max_d: 1.0
  map_decay_time: 120 # sec
  map_decay_dist: 100 # m
  map_icp_dist: 5 # m
  map_use_icp: false
  plane_max_p2pd: 0.1
  plane_max_condi: 200.0

lidar0:
  timeoffset: 0.0
  T_imu_lidar:
   # - [  0.7044134,  0.7097900,  0.0000000]
   # - [ -0.0005652,  0.0005609,  0.9999997]
   # - [  0.7097898, -0.7044132,  0.0007963]
   - [ 1, 0, 0]
   - [ 0.0000000, -0.7043476, -0.7098553]
   - [ 0.0000000,  0.7098553, -0.7043476]
   # - [ 0, -1, 0]
   # - [ 0, 0, -1]
  v_angles: [-80,-70,-60,-50,-40,-30,-20,-10,0,10,20,30,40,50,60,70,80]
#  v_angles: [-15.0, -13.0, -11.0, -9.0, -7.0, -5.0, -3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0]
#  h_resolution: 0.5
#  h_resolution: 1.0
  h_resolution: 0.1
  h_start: -180
  h_end: 180
  topic: "/uav46/picoflexx_back/pcl_filtered"

lidar1:
  timeoffset: 0.0
  T_imu_lidar:
    - [ 1, 0, 0]
    - [ 0, 1, 0]
    - [ 0, 0, 1]
  v_angles: [-80,-70,-60,-50,-40,-30,-20,-10,0,10,20,30,40,50,60,70,80]
#  v_angles: [-15.0, -13.0, -11.0, -9.0, -7.0, -5.0, -3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0]
#  h_resolution: 1.0
  h_resolution: 0.1
  h_start: -180
  h_end: 180
  topic: "/uav46/picoflexx_left/pcl_filtered"
lidar2:
  timeoffset: 0.0
  T_imu_lidar:
    - [0.0,-1.0, 0.0, 0.1]
    - [1.0, 0.0, 0.0, 0.1]
    - [0.0, 0.0, 1.0, 0.1]
    - [0.0, 0.0, 0.0, 1.0]
  v_angles: [-15.0, -13.0, -11.0, -9.0, -7.0, -5.0, -3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0]
  h_resolution: 1.0
  h_start: -180
  h_end: 180
  topic: ""
lidar3:
  timeoffset: 0.0
  T_imu_lidar:
    - [ 0.0, 1.0, 0.0,-1.0]
    - [-1.0, 0.0, 0.0,-1.0]
    - [ 0.0, 0.0, 1.0,-1.0]
    - [ 0.0, 0.0, 0.0, 1.0]
  v_angles: [-15.0, -13.0, -11.0, -9.0, -7.0, -5.0, -3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0]
  h_resolution: 1.0
  h_start: -180
  h_end: 180
  topic: ""
lidar4:
  timeoffset: 0.0
  T_imu_lidar:
    - [ 0.0, 1.0, 0.0,-1.0]
    - [-1.0, 0.0, 0.0,-1.0]
    - [ 0.0, 0.0, 1.0,-1.0]
    - [ 0.0, 0.0, 0.0, 1.0]
  v_angles: [-15.0, -13.0, -11.0, -9.0, -7.0, -5.0, -3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0]
  h_resolution: 1.0
  h_start: -180
  h_end: 180
  topic: ""
